CRM_DATABASE = {
    "ORD001": {
        "customer_id": "C001",
        "name": "Priya Sharma",
        "email": "priya@example.com",
        "tier": "Gold",
        "order_id": "ORD001",
        "product": "Wireless Headphones",
        "category": "Electronics",
        "amount": 2999,
        "purchase_date": "2025-05-20",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-25",
        "item_condition": "Damaged",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD002": {
        "customer_id": "C002",
        "name": "Rahul Mehta",
        "email": "rahul@example.com",
        "tier": "Standard",
        "order_id": "ORD002",
        "product": "Python Course (Digital)",
        "category": "Digital",
        "amount": 1499,
        "purchase_date": "2025-06-01",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-01",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": True,
        "is_sale_item": False
    },
    "ORD003": {
        "customer_id": "C003",
        "name": "Anjali Patel",
        "email": "anjali@example.com",
        "tier": "Platinum",
        "order_id": "ORD003",
        "product": "Running Shoes",
        "category": "Footwear",
        "amount": 4500,
        "purchase_date": "2025-04-01",
        "delivery_status": "Delivered",
        "delivery_date": "2025-04-05",
        "item_condition": "Used",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD004": {
        "customer_id": "C004",
        "name": "Vikram Singh",
        "email": "vikram@example.com",
        "tier": "Standard",
        "order_id": "ORD004",
        "product": "Bluetooth Speaker",
        "category": "Electronics",
        "amount": 1800,
        "purchase_date": "2025-06-10",
        "delivery_status": "Not Delivered",
        "delivery_date": None,
        "item_condition": "N/A",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD005": {
        "customer_id": "C005",
        "name": "Sneha Rao",
        "email": "sneha@example.com",
        "tier": "Standard",
        "order_id": "ORD005",
        "product": "Clearance T-Shirt",
        "category": "Clothing",
        "amount": 299,
        "purchase_date": "2025-06-12",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-14",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": True
    },
    "ORD006": {
        "customer_id": "C006",
        "name": "Arjun Nair",
        "email": "arjun@example.com",
        "tier": "Gold",
        "order_id": "ORD006",
        "product": "Smart Watch",
        "category": "Electronics",
        "amount": 8999,
        "purchase_date": "2025-06-15",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-17",
        "item_condition": "Wrong Item",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD007": {
        "customer_id": "C007",
        "name": "Divya Krishnan",
        "email": "divya@example.com",
        "tier": "Standard",
        "order_id": "ORD007",
        "product": "Coffee Maker",
        "category": "Appliances",
        "amount": 3200,
        "purchase_date": "2025-03-01",
        "delivery_status": "Delivered",
        "delivery_date": "2025-03-05",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD008": {
        "customer_id": "C008",
        "name": "Karan Malhotra",
        "email": "karan@example.com",
        "tier": "Standard",
        "order_id": "ORD008",
        "product": "Gaming Mouse",
        "category": "Electronics",
        "amount": 2100,
        "purchase_date": "2025-06-05",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-08",
        "item_condition": "Defective",
        "last_refund_date": "2025-04-01",
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD009": {
        "customer_id": "C009",
        "name": "Meera Iyer",
        "email": "meera@example.com",
        "tier": "Platinum",
        "order_id": "ORD009",
        "product": "Yoga Mat",
        "category": "Sports",
        "amount": 899,
        "purchase_date": "2025-05-10",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-13",
        "item_condition": "Damaged",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD010": {
        "customer_id": "C010",
        "name": "Rohan Gupta",
        "email": "rohan@example.com",
        "tier": "Standard",
        "order_id": "ORD010",
        "product": "Desk Lamp",
        "category": "Home",
        "amount": 750,
        "purchase_date": "2025-06-01",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-04",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD011": {
        "customer_id": "C011",
        "name": "Pooja Verma",
        "email": "pooja@example.com",
        "tier": "Gold",
        "order_id": "ORD011",
        "product": "Air Purifier",
        "category": "Appliances",
        "amount": 12000,
        "purchase_date": "2025-06-10",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-13",
        "item_condition": "Defective",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD012": {
        "customer_id": "C012",
        "name": "Amit Joshi",
        "email": "amit@example.com",
        "tier": "Standard",
        "order_id": "ORD012",
        "product": "Backpack",
        "category": "Bags",
        "amount": 1200,
        "purchase_date": "2025-06-14",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-16",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD013": {
        "customer_id": "C013",
        "name": "Kavya Reddy",
        "email": "kavya@example.com",
        "tier": "Standard",
        "order_id": "ORD013",
        "product": "Sunglasses",
        "category": "Accessories",
        "amount": 650,
        "purchase_date": "2025-06-17",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-18",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD014": {
        "customer_id": "C014",
        "name": "Sanjay Bhatt",
        "email": "sanjay@example.com",
        "tier": "Standard",
        "order_id": "ORD014",
        "product": "Protein Powder",
        "category": "Health",
        "amount": 1800,
        "purchase_date": "2025-06-12",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-15",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD015": {
        "customer_id": "C015",
        "name": "Nisha Kapoor",
        "email": "nisha@example.com",
        "tier": "Gold",
        "order_id": "ORD015",
        "product": "Laptop Stand",
        "category": "Accessories",
        "amount": 2200,
        "purchase_date": "2025-04-10",
        "delivery_status": "Delivered",
        "delivery_date": "2025-04-13",
        "item_condition": "Damaged",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD016": {
        "customer_id": "C016",
        "name": "Sameer Sen",
        "email": "sameer@example.com",
        "tier": "Standard",
        "order_id": "ORD016",
        "product": "Gaming Keyboard",
        "category": "Electronics",
        "amount": 3499,
        "purchase_date": "2025-06-15",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-16",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD017": {
        "customer_id": "C017",
        "name": "Riya Sen",
        "email": "riya@example.com",
        "tier": "Platinum",
        "order_id": "ORD017",
        "product": "Winter Jacket",
        "category": "Clothing",
        "amount": 7999,
        "purchase_date": "2025-05-02",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-05",
        "item_condition": "Damaged",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD018": {
        "customer_id": "C018",
        "name": "Pranav Shah",
        "email": "pranav@example.com",
        "tier": "Gold",
        "order_id": "ORD018",
        "product": "SaaS Subscription (Monthly)",
        "category": "Digital",
        "amount": 999,
        "purchase_date": "2025-06-17",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-17",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": True,
        "is_sale_item": False
    },
    "ORD019": {
        "customer_id": "C019",
        "name": "Jyoti Sharma",
        "email": "jyoti@example.com",
        "tier": "Standard",
        "order_id": "ORD019",
        "product": "Office Chair",
        "category": "Home",
        "amount": 5400,
        "purchase_date": "2025-06-12",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-14",
        "item_condition": "Damaged",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD020": {
        "customer_id": "C020",
        "name": "Deepak Verma",
        "email": "deepak@example.com",
        "tier": "Standard",
        "order_id": "ORD020",
        "product": "Dumbbells Set",
        "category": "Sports",
        "amount": 2499,
        "purchase_date": "2025-06-16",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-18",
        "item_condition": "Wrong Item",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD021": {
        "customer_id": "C021",
        "name": "Tanvi Rao",
        "email": "tanvi@example.com",
        "tier": "Gold",
        "order_id": "ORD021",
        "product": "Mechanical Keyboard",
        "category": "Electronics",
        "amount": 4200,
        "purchase_date": "2025-05-25",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-28",
        "item_condition": "Defective",
        "last_refund_date": "2025-05-10",
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD022": {
        "customer_id": "C022",
        "name": "Madhav Nair",
        "email": "madhav@example.com",
        "tier": "Standard",
        "order_id": "ORD022",
        "product": "Hardcover Novel",
        "category": "Books",
        "amount": 599,
        "purchase_date": "2025-06-14",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-16",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": True
    },
    "ORD023": {
        "customer_id": "C023",
        "name": "Simran Gill",
        "email": "simran@example.com",
        "tier": "Platinum",
        "order_id": "ORD023",
        "product": "Noise Cancelling Earbuds",
        "category": "Electronics",
        "amount": 12999,
        "purchase_date": "2025-05-28",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-30",
        "item_condition": "Damaged",
        "last_refund_date": "2025-02-15",
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD024": {
        "customer_id": "C024",
        "name": "Yash Patel",
        "email": "yash@example.com",
        "tier": "Standard",
        "order_id": "ORD024",
        "product": "Electric Kettle",
        "category": "Home",
        "amount": 1599,
        "purchase_date": "2025-05-05",
        "delivery_status": "Delivered",
        "delivery_date": "2025-05-08",
        "item_condition": "Defective",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD025": {
        "customer_id": "C025",
        "name": "Aishwarya Sen",
        "email": "aishwarya@example.com",
        "tier": "Standard",
        "order_id": "ORD025",
        "product": "Designer Shoes",
        "category": "Clothing",
        "amount": 5500,
        "purchase_date": "2025-06-08",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-10",
        "item_condition": "Used",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD026": {
        "customer_id": "C026",
        "name": "Kunal Deshmukh",
        "email": "kunal@example.com",
        "tier": "Gold",
        "order_id": "ORD026",
        "product": "Graphic Design Templates",
        "category": "Digital",
        "amount": 1999,
        "purchase_date": "2025-06-18",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-18",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": True,
        "is_sale_item": False
    },
    "ORD027": {
        "customer_id": "C027",
        "name": "Nidhi Malhotra",
        "email": "nidhi@example.com",
        "tier": "Standard",
        "order_id": "ORD027",
        "product": "USB-C Hub",
        "category": "Electronics",
        "amount": 999,
        "purchase_date": "2025-06-13",
        "delivery_status": "Not Delivered",
        "delivery_date": None,
        "item_condition": "N/A",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD028": {
        "customer_id": "C028",
        "name": "Varun Johar",
        "email": "varun@example.com",
        "tier": "Standard",
        "order_id": "ORD028",
        "product": "Tennis Racket",
        "category": "Sports",
        "amount": 3500,
        "purchase_date": "2025-05-12",
        "delivery_status": "Not Delivered",
        "delivery_date": None,
        "item_condition": "N/A",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD029": {
        "customer_id": "C029",
        "name": "Ritika Sen",
        "email": "ritika@example.com",
        "tier": "Gold",
        "order_id": "ORD029",
        "product": "Air Fryer",
        "category": "Appliances",
        "amount": 6500,
        "purchase_date": "2025-06-05",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-08",
        "item_condition": "Defective",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": False
    },
    "ORD030": {
        "customer_id": "C030",
        "name": "Gaurav Roy",
        "email": "gaurav@example.com",
        "tier": "Standard",
        "order_id": "ORD030",
        "product": "Leather Wallet",
        "category": "Clothing",
        "amount": 1200,
        "purchase_date": "2025-06-16",
        "delivery_status": "Delivered",
        "delivery_date": "2025-06-18",
        "item_condition": "Good",
        "last_refund_date": None,
        "is_digital": False,
        "is_sale_item": True
    },
}

import copy
INITIAL_CRM_DATABASE = copy.deepcopy(CRM_DATABASE)

def reset_crm_database():
    CRM_DATABASE.clear()
    CRM_DATABASE.update(copy.deepcopy(INITIAL_CRM_DATABASE))